taco integration
simit-lang/simit pull request #108
Opened 2017-07-17 17:34 UTC by huangjd

2017-08-07 03:13 UTC, stephenchouca requested changes

2017-08-07 03:13 UTC, stephenchouca commented on src/lower/lower_indexexpr_taco.cpp
> +// For example  A(i,j) = B(i,k)*B(k,j), where B is {Dense, Sparse}
Is this actually an issue? taco seems to be able to generate code for the particular example in the comment.

2017-08-07 03:13 UTC, stephenchouca commented on src/lower/lower_indexexpr_taco.cpp
> +  func = insertInitializations(func); /// @todo needed due to bugs in taco
Is this still needed with the latest version of taco? I believe it should now generate output initialization code as well.

2017-08-07 03:13 UTC, stephenchouca commented on src/lower/lower_indexexpr_taco.cpp
> +    tacoAccess = Ptr(new taco::IndexExpr(*a * *b));
Enclose `*a` and `*b` with parentheses to avoid confusion.

2017-08-07 03:13 UTC, stephenchouca commented on src/lower/lower_indexexpr_taco.cpp
> +    tacoAccess = Ptr(new taco::IndexExpr(*a - *b));
Enclose `*a` and `*b` with parentheses to avoid confusion.

2017-08-07 03:13 UTC, stephenchouca commented on src/lower/lower_indexexpr_taco.cpp
> +    tacoAccess = Ptr(new taco::IndexExpr(*a + *b));
Enclose `*a` and `*b` with parentheses to avoid confusion.

2017-08-07 03:13 UTC, stephenchouca commented on src/lower/lower_indexexpr_taco.cpp
> +    tacoAccess = Ptr(new taco::IndexExpr(-*a));
Enclose `*a` with parentheses to avoid confusion.

2017-08-07 03:13 UTC, stephenchouca commented on src/lower/lower_indexexpr_taco.cpp
> +    tacoAccess = Ptr(new taco::IndexExpr(*a / *b));;
Enclose `*a` and `*b` with parentheses to avoid confusion.

2017-08-08 10:38 UTC, huangjd commented
Taco should throw exception on error, instead of calling abort(), since there's no way to recover from that

2017-08-08 10:39 UTC, huangjd commented
Taco should throw exception on error instead of calling abort(), since there's no way to recover from that

2018-09-11 02:25 UTC, merged